const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const originInput=$('#origin'), destinationInput=$('#destination');
const HUBS=[
 ['berger','Berger Junction',9.0667,7.4431],['wuse','Wuse Market',9.0765,7.4623],['area1','Garki Area 1',9.0358,7.4881],['garki','Garki Market',9.0304,7.4898],['central','Central Area',9.0556,7.4914],['jabi','Jabi Park',9.0655,7.4207],['utako','Utako Motor Park',9.0679,7.4498],['mabushi','Mabushi',9.0834,7.4534],['gwarinpa','Gwarinpa',9.1098,7.4055],['kubwa','Kubwa',9.1544,7.3220],['lugbe','Lugbe',8.9778,7.3724],['airportRd','Airport Road Junction',9.0038,7.3957],['nyanya','Nyanya',9.0251,7.5681],['mararaba','Mararaba',9.0312,7.5885],['asokoro','Asokoro',9.0361,7.5247],['maitama','Maitama',9.0873,7.4934],['apo','Apo',8.9898,7.4992],['karu','Karu',9.0098,7.5695],['lifeCamp','Life Camp',9.0805,7.3908],['dutse','Dutse Alhaji',9.1328,7.3907]
].map(([id,name,lat,lng])=>({id,name,lat,lng,source:'prototype'}));
const H=Object.fromEntries(HUBS.map(h=>[h.id,h]));
const LINKS=[
 ['berger','utako','bus',250,350,7],['utako','jabi','bus',250,400,9],['jabi','lifeCamp','keke',250,350,8],['lifeCamp','gwarinpa','bus',350,500,12],['gwarinpa','dutse','keke',250,400,10],['dutse','kubwa','bus',400,600,18],
 ['berger','wuse','bus',400,550,14],['wuse','central','bus',300,450,10],['central','area1','bus',300,450,11],['area1','garki','keke',200,300,6],['garki','apo','keke',250,400,10],
 ['wuse','mabushi','keke',250,350,8],['mabushi','maitama','taxi',350,500,9],['maitama','central','taxi',350,550,10],['central','asokoro','taxi',400,650,12],['asokoro','karu','taxi',450,700,15],['karu','nyanya','bus',250,400,9],['nyanya','mararaba','bus',300,500,11],
 ['berger','airportRd','bus',400,600,15],['airportRd','lugbe','bus',350,550,14],['airportRd','apo','taxi',450,650,14],['apo','area1','keke',250,400,9],['utako','mabushi','keke',250,400,8],['jabi','gwarinpa','bus',350,500,14],['wuse','maitama','taxi',300,500,10],['garki','asokoro','taxi',350,550,11],['area1','karu','bus',450,650,15],['central','nyanya','bus',500,750,20],['berger','central','bus',450,650,16],['kubwa','gwarinpa','bus',450,650,18],['lugbe','apo','bus',450,650,17],['mabushi','central','bus',300,450,10]
].map((e,i)=>({id:`route-${i+1}`,a:e[0],b:e[1],mode:e[2],fareMin:e[3],fareMax:e[4],minutes:e[5],confidence:i<12?'High':'Medium',source:'prototype'}));
const state={origin:null,destination:null,routes:[],selected:0,pickMode:null,navStep:0,voice:true,paused:false,voiceName:localStorage.getItem('alongVoice')||'browser',routeLayer:null,markerLayer:null};
const map=L.map('map',{zoomControl:true,minZoom:9}).setView([9.0556,7.4914],12);
const tileUrl=['https:','','tile.openstreetmap.org','{z}','{x}','{y}.png'].join('/');
L.tileLayer(tileUrl,{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
map.zoomControl.setPosition('topright');
const networkLayer=L.layerGroup().addTo(map), hubLayer=L.layerGroup().addTo(map);
const iconHtml=(color='#171817')=>L.divIcon({className:'along-marker-wrap',html:`<span class="along-marker" style="--marker:${color}"><i></i></span>`,iconSize:[28,28],iconAnchor:[14,14]});
LINKS.forEach(e=>L.polyline([[H[e.a].lat,H[e.a].lng],[H[e.b].lat,H[e.b].lng]],{color:e.mode==='bus'?'#8a72e8':e.mode==='keke'?'#d08a3d':'#69716b',weight:3,opacity:.2,dashArray:e.mode==='taxi'?'5 8':null}).addTo(networkLayer));
HUBS.forEach(h=>L.marker([h.lat,h.lng],{icon:iconHtml('#171817')}).bindTooltip(h.name,{direction:'top'}).addTo(hubLayer));
L.control.layers(null,{'Prototype transport routes':networkLayer,'Transport hubs':hubLayer},{collapsed:true,position:'topright'}).addTo(map);
function km(a,b){const R=6371,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p,s=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function nearestHub(p){return HUBS.reduce((best,h)=>km(p,h)<best.distance?{hub:h,distance:km(p,h)}:best,{hub:HUBS[0],distance:Infinity})}
function money(n){return`₦${Math.round(n).toLocaleString('en-NG')}`} function modeIcon(m){return({walk:'↗',bus:'▰',keke:'◉',taxi:'◆'})[m]||'→'}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),3000)}
function graphRoute(start,end,preference='fast'){const dist={},prev={},queue=new Set(HUBS.map(h=>h.id));HUBS.forEach(h=>dist[h.id]=Infinity);dist[start]=0;while(queue.size){let u=[...queue].reduce((a,b)=>dist[a]<dist[b]?a:b);if(!Number.isFinite(dist[u]))break;queue.delete(u);if(u===end)break;for(const e of LINKS.filter(x=>x.a===u||x.b===u)){const v=e.a===u?e.b:e.a;if(!queue.has(v))continue;const weight=preference==='cheap'?e.fareMin/25+e.minutes:preference==='simple'?e.minutes+(e.mode==='keke'?5:0):e.minutes+e.fareMin/100;const alt=dist[u]+weight;if(alt<dist[v]){dist[v]=alt;prev[v]={from:u,edge:e}}}}if(!prev[end]&&start!==end)return null;const edges=[];let cur=end;while(cur!==start){const p=prev[cur];if(!p)return null;edges.unshift({...p.edge,from:p.from,to:cur});cur=p.from}return edges}
function buildJourney(origin,destination,preference,label){const a=nearestHub(origin),b=nearestHub(destination),edges=graphRoute(a.hub.id,b.hub.id,preference)||[];const legs=[];if(a.distance>.05)legs.push({mode:'walk',from:origin.name,to:a.hub.name,distance:Math.round(a.distance*1000),time:Math.max(2,Math.round(a.distance*12)),text:`Walk to ${a.hub.name}, your nearest supported Along stop.`,coords:[[origin.lat,origin.lng],[a.hub.lat,a.hub.lng]]});edges.forEach((e,i)=>{const f=H[e.from],t=H[e.to],dir=t.name;legs.push({mode:e.mode,from:f.name,to:t.name,time:e.minutes,fare:[e.fareMin,e.fareMax],text:`Take a ${e.mode} going to ${dir}. Drop at ${t.name}.`,coords:[[f.lat,f.lng],[t.lat,t.lng]],confidence:e.confidence})});if(b.distance>.05)legs.push({mode:'walk',from:b.hub.name,to:destination.name,distance:Math.round(b.distance*1000),time:Math.max(2,Math.round(b.distance*12)),text:`Walk from ${b.hub.name} to ${destination.name}.`,coords:[[b.hub.lat,b.hub.lng],[destination.lat,destination.lng]]});if(!legs.length)legs.push({mode:'walk',from:origin.name,to:destination.name,distance:Math.round(km(origin,destination)*1000),time:Math.round(km(origin,destination)*12),text:`Walk to ${destination.name}.`,coords:[[origin.lat,origin.lng],[destination.lat,destination.lng]]});const fares=legs.filter(l=>l.fare),walk=legs.filter(l=>l.mode==='walk').reduce((s,l)=>s+(l.distance||0),0),modes=legs.map(l=>l.mode),changes=Math.max(0,legs.filter(l=>l.mode!=='walk').length-1);return{label,legs,time:legs.reduce((s,l)=>s+l.time,0),fare:[fares.reduce((s,l)=>s+l.fare[0],0),fares.reduce((s,l)=>s+l.fare[1],0)],walk,transfers:changes,confidence:edges.every(e=>e.confidence==='High')?'High':'Medium',modes,origin,destination}}
async function geocode(query){
  const clean=query.trim();
  try{const u=new URL('/api/geocode',location.origin);u.searchParams.set('q',clean);const r=await fetch(u);if(r.ok){const x=await r.json();if(x.results?.length)return x.results.map(v=>({...v,type:'search'}))}}catch{}
  try{const u=new URL('https://nominatim.openstreetmap.org/search');u.search=new URLSearchParams({q:clean,format:'jsonv2',limit:'8',addressdetails:'1',countrycodes:'ng',viewbox:'7.20,9.30,7.75,8.80',bounded:'0'});const r=await fetch(u,{headers:{'Accept-Language':'en-NG,en'}});if(r.ok){const items=(await r.json()).map(x=>({name:x.display_name,lat:+x.lat,lng:+x.lon,type:'search'}));if(items.length)return items}}catch{}
  try{const u=new URL('https://photon.komoot.io/api/');u.search=new URLSearchParams({q:clean,limit:'8',lat:'9.0556',lon:'7.4914',lang:'en'});const r=await fetch(u);if(r.ok)return(await r.json()).features.filter(x=>x.properties.countrycode==='NG').map(x=>({name:[x.properties.name,x.properties.street,x.properties.district,x.properties.city,x.properties.state].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).slice(0,4).join(', '),lat:x.geometry.coordinates[1],lng:x.geometry.coordinates[0],type:'search'}))}catch{}
  return[]
}
async function reverseGeocode(lat,lng){
  try{const u=new URL('/api/geocode',location.origin);u.search=new URLSearchParams({lat,lon:lng});const r=await fetch(u);if(r.ok){const x=await r.json();if(x.results?.[0])return x.results[0].name}}catch{}
  try{const u=new URL('https://nominatim.openstreetmap.org/reverse');u.search=new URLSearchParams({lat,lon:lng,format:'jsonv2',zoom:'18'});const r=await fetch(u,{headers:{'Accept-Language':'en-NG,en'}}),x=await r.json();return x.display_name||'Dropped pin'}catch{return'Dropped pin'}
}
function localMatch(q){q=q.toLowerCase().trim();return HUBS.filter(h=>h.name.toLowerCase().includes(q)).slice(0,5)}
let searchTimer;
function setupSearch(input,resultEl,key){input.addEventListener('input',()=>{state[key]=null;clearTimeout(searchTimer);const local=localMatch(input.value);renderSuggestions(local,resultEl,input,key);if(input.value.trim().length<3)return;searchTimer=setTimeout(async()=>{try{const remote=await geocode(input.value);renderSuggestions([...local,...remote].slice(0,6),resultEl,input,key)}catch{if(!local.length)showToast('Online place search is unavailable. Pick from the map instead.')}},900)});input.addEventListener('focus',()=>{const local=localMatch(input.value);if(local.length)renderSuggestions(local,resultEl,input,key)})}
function renderSuggestions(items,el,input,key){el.innerHTML=items.map((x,i)=>`<button type="button" data-i="${i}">${x.name}<small>${x.type==='search'?'OpenStreetMap place':'Along transport hub'}</small></button>`).join('');el.hidden=!items.length;[...el.children].forEach((b,i)=>b.onclick=()=>{state[key]=items[i];input.value=items[i].name;el.hidden=true;map.flyTo([items[i].lat,items[i].lng],14)})}
async function resolveInput(input,key){if(state[key])return state[key];const local=HUBS.find(h=>h.name.toLowerCase()===input.value.trim().toLowerCase());if(local)return state[key]=local;const found=await geocode(input.value);if(!found[0])throw Error(`We couldn't find ${input.value} in Abuja.`);input.value=found[0].name;return state[key]=found[0]}
async function submitRoute(){const btn=$('#routeForm button[type=submit]'),label=btn.querySelector('.btn-label');label.textContent='Finding route…';btn.disabled=true;try{const [o,d]=await Promise.all([resolveInput(originInput,'origin'),resolveInput(destinationInput,'destination')]);if(km(o,d)<.05)throw Error('Choose two different places.');const abuja={lat:9.0556,lng:7.4914};if(km(o,abuja)>90||km(d,abuja)>90)throw Error('Along currently supports journeys connected to the Abuja network.');state.routes=[buildJourney(o,d,'fast','Fastest'),buildJourney(o,d,'cheap','Cheapest'),buildJourney(o,d,'simple','Fewer changes')];state.selected=0;$('#plannerPanel').hidden=true;$('#resultsPanel').hidden=false;$('#resultsTitle').textContent=`${o.name} to ${d.name}`;renderTabs();renderRoute()}catch(e){showToast(e.message||'We could not build this route.')}finally{label.textContent='Find my route';btn.disabled=false}}
function renderTabs(){const el=$('#routeTabs');el.innerHTML=state.routes.map((r,i)=>`<button class="route-tab ${i===state.selected?'active':''}" data-route="${i}"><b>${r.label}</b><small>${r.time} min · ${money(r.fare[0])}+</small></button>`).join('');$$('[data-route]').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.route;renderTabs();renderRoute()})}
function renderRoute(){const r=state.routes[state.selected];if(state.routeLayer)map.removeLayer(state.routeLayer);const group=[];r.legs.forEach(l=>{const color=l.mode==='walk'?'#171817':l.mode==='bus'?'#8067e6':l.mode==='keke'?'#d48635':'#65706a';group.push(L.polyline(l.coords,{color,weight:l.mode==='walk'?5:7,dashArray:l.mode==='walk'?'3 10':null,opacity:.95}))});group.push(L.marker([r.origin.lat,r.origin.lng],{icon:iconHtml('#b8f04a')}).bindTooltip('Start'));group.push(L.marker([r.destination.lat,r.destination.lng],{icon:iconHtml('#8a72e8')}).bindTooltip('Destination'));state.routeLayer=L.featureGroup(group).addTo(map);map.fitBounds(state.routeLayer.getBounds().pad(.22));const legs=r.legs.map(l=>`<div class="leg ${l.mode!=='walk'?'transport':''}"><div class="leg-icon">${modeIcon(l.mode)}</div><div><h3>${l.mode[0].toUpperCase()+l.mode.slice(1)} · ${l.from} → ${l.to}</h3><p>${l.text}</p>${l.fare?`<p class="fare">Approx. ${money(l.fare[0])}–${money(l.fare[1])}</p>`:''}</div></div>`).join('');$('#routeSummary').innerHTML=`<div class="summary-card"><div class="metrics"><div class="metric"><b>${r.time} min</b><span>Total time</span></div><div class="metric"><b>${money(r.fare[0])}–${money(r.fare[1])}</b><span>Fare range</span></div><div class="metric"><b>${r.transfers}</b><span>Transfers</span></div><div class="metric"><b>${r.walk}m</b><span>Walking</span></div></div><div class="modes">${r.modes.map(m=>m[0].toUpperCase()+m.slice(1)).join(' → ')}</div><span class="confidence">● ${r.confidence} confidence · prototype</span></div><div class="timeline">${legs}</div><p class="fare-note">Fares and route availability can vary. Confirm with the driver before entering.</p><button class="primary-btn" id="startNavBtn">Start navigation <span>→</span></button>`;$('#startNavBtn').onclick=startNavigation;setTimeout(()=>map.invalidateSize(),80)}
function startNavigation(){state.navStep=0;state.paused=false;document.body.classList.add('nav-active');$('#resultsPanel').hidden=true;$('#navigationPanel').hidden=false;$('#voiceSelect').value=state.voiceName;updateNav();speak('Navigation started. '+state.routes[state.selected].legs[0].text);setTimeout(()=>map.invalidateSize(),100)}
function updateNav(){const r=state.routes[state.selected],l=r.legs[state.navStep];if(!l){$('#navInstruction').textContent="You've arrived";$('#navDistance').textContent=r.destination.name;$('#navModeIcon').textContent='✓';$('#navStepNumber').textContent='COMPLETE';$('#navProgress').style.width='100%';$('#nextStepBtn').textContent='Trip complete';speak(`You've arrived at ${r.destination.name}.`);return}$('#navStepNumber').textContent=`${state.navStep+1} OF ${r.legs.length}`;$('#navInstruction').textContent=l.text;$('#navDistance').textContent=l.distance?`${l.distance} metres away`:`About ${l.time} minutes`;$('#navModeIcon').textContent=modeIcon(l.mode);$('#navProgress').style.width=`${Math.max(12,state.navStep/r.legs.length*100)}%`;map.fitBounds(L.latLngBounds(l.coords).pad(.8))}
async function speak(text){if(!state.voice)return;const cloud=state.voiceName!=='browser';if(cloud){try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:state.voiceName})});if(r.ok){const audio=new Audio(URL.createObjectURL(await r.blob()));await audio.play();return}}catch{}}if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),ng=voices.find(v=>v.lang.toLowerCase()==='en-ng')||voices.find(v=>v.lang.toLowerCase().startsWith('en-'));const u=new SpeechSynthesisUtterance(text);if(ng)u.voice=ng;u.lang=ng?.lang||'en-NG';u.rate=.94;speechSynthesis.speak(u);if(cloud)showToast('Online Nigerian voice is not configured; using your device voice.')}
$('#routeForm').onsubmit=e=>{e.preventDefault();submitRoute()};
setupSearch(originInput,$('#originResults'),'origin');setupSearch(destinationInput,$('#destinationResults'),'destination');
$('#swapBtn').onclick=()=>{[originInput.value,destinationInput.value]=[destinationInput.value,originInput.value];[state.origin,state.destination]=[state.destination,state.origin]};
$$('[data-trip]').forEach(b=>b.onclick=()=>{const[a,d]=b.dataset.trip.split('|');originInput.value=a;destinationInput.value=d;state.origin=HUBS.find(h=>h.name===a)||null;state.destination=HUBS.find(h=>h.name===d)||null;submitRoute()});
$$('[data-pick]').forEach(b=>b.onclick=()=>{state.pickMode=b.dataset.pick;$('#pickTarget').textContent=state.pickMode;$('#pickBanner').hidden=false;map.getContainer().classList.add('picking');showToast(`Tap the map to set ${state.pickMode}`)});$('#cancelPick').onclick=()=>{state.pickMode=null;$('#pickBanner').hidden=true;map.getContainer().classList.remove('picking')};
map.on('click',async e=>{if(!state.pickMode)return;const key=state.pickMode,input=key==='origin'?originInput:destinationInput;input.value='Dropped pin…';const name=await reverseGeocode(e.latlng.lat,e.latlng.lng);state[key]={name,lat:e.latlng.lat,lng:e.latlng.lng,type:'pin'};input.value=name;state.pickMode=null;$('#pickBanner').hidden=true;map.getContainer().classList.remove('picking');L.marker(e.latlng,{icon:iconHtml(key==='origin'?'#b8f04a':'#8a72e8')}).addTo(map).bindTooltip(key==='origin'?'Origin':'Destination').openTooltip()});
$('#locateBtn').onclick=()=>{if(!navigator.geolocation)return showToast('Location is unavailable on this device.');showToast('Finding your location…');navigator.geolocation.getCurrentPosition(async p=>{const{x:lng,y:lat}=p.coords;const name=await reverseGeocode(lat,lng);state.origin={name,lat,lng,type:'gps'};originInput.value=name;map.flyTo([lat,lng],15);showToast('Current location added.')},()=>showToast("We couldn't access your location. Search or pick from the map."),{enableHighAccuracy:true,timeout:8000})};
$('#editTripBtn').onclick=()=>{$('#resultsPanel').hidden=true;$('#plannerPanel').hidden=false;setTimeout(()=>map.invalidateSize(),80)};$('#nextStepBtn').onclick=()=>{if(state.paused)return showToast('Resume the trip first.');const l=state.routes[state.selected].legs[state.navStep];if(!l)return;state.navStep++;updateNav();const next=state.routes[state.selected].legs[state.navStep];if(next)speak(`You've reached ${l.to}. ${next.text}`)};$('#pauseBtn').onclick=()=>{state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'Resume':'Pause'};$('#voiceBtn').onclick=()=>{state.voice=!state.voice;$('#voiceBtn').textContent=state.voice?'🔊':'🔇';showToast(`Voice ${state.voice?'on':'off'}`)};$('#closeNavBtn').onclick=()=>{document.body.classList.remove('nav-active');$('#navigationPanel').hidden=true;$('#resultsPanel').hidden=false;speechSynthesis?.cancel();setTimeout(()=>map.invalidateSize(),80)};
$('#voiceSelect').onchange=e=>{state.voiceName=e.target.value;$('#settingsVoice').value=state.voiceName;localStorage.setItem('alongVoice',state.voiceName)};$('#settingsBtn').onclick=()=>{$('#settingsVoice').value=state.voiceName;$('#settingsDialog').showModal()};$('#settingsVoice').onchange=e=>{state.voiceName=e.target.value;$('#voiceSelect').value=state.voiceName;localStorage.setItem('alongVoice',state.voiceName)};
$('#reportBtn').onclick=()=>$('#reportDialog').showModal();$('#reportForm').addEventListener('submit',()=>setTimeout(()=>showToast('Thanks — your report was saved for review.'),100));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});setTimeout(()=>map.invalidateSize(),100);
